Beyond-Imagination/fienmee

ecosystem.dev.config.json
package.json
pnpm-lock.yaml

chore: pm2

---

.gitignore
apps/server/.swcrc
apps/server/package.json
apps/server/src/app.ts
apps/server/src/config/index.ts
apps/server/src/server.ts
apps/server/src/utils/logger.ts
apps/server/tsconfig.json
pnpm-lock.yaml
tsconfig.base.json

feat: server

---

apps/server/.env.template
apps/server/package.json
apps/server/src/config/index.ts
apps/server/src/models/connector.ts
pnpm-lock.yaml

* mongoose model을 사용하기 위한 connector를 추가합니다.

chore: add 'mongoose' connector

---

apps/web/next.config.ts
package.json

chore: ssg build for web

---

.husky/pre-commit
apps/web/.eslintrc.json

fe 의 eslint 설정에 root를 추가합니다
그리고 pre commit hook 을 수정해 commit 시 next lint 가 실행되도록 하였습니다

chore: set sub root eslint configure for web

---

apps/server/package.json
apps/server/src/models/enquiry.ts
pnpm-lock.yaml

현재 `user` 모델이 정의가 되어 있지 않아, userId를 레퍼런스 없이 정의하였습니다. 추후 필요한 경우 수정이 필요합니다.

feat: add Enquiry model

---

apps/server/src/models/event.ts
apps/server/src/models/schedule.ts

comments의 경우 comment model이 선언되어 있지 않아 레퍼런스를 지정하지 않았습니다.
추후 수정 가능합니다.

feat: add Events model

---

apps/server/src/controllers/v1/events.ts

feat: add /v1/events PUT API

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts

특정 행사 정보를 가져오는 API 입니다.
유저 미들웨어 추가 시 유저가 행사에 좋아요를 표시했는지의 여부를 반환 정보에 포함시킬 수 있습니다.

feat: add GET API to get a event detail

---

apps/server/package.json
apps/server/src/controllers/v1/schedule.ts
apps/server/src/models/schedule.ts
pnpm-lock.yaml

* userId 를 requestBody에 포함시킬 수 있게끔 auth middleware에서 sanitize해주는 것이 필요합니다.
* 이 과정에서 임의로 삽입된 userId는 overwrite되도록 만드는 것이 좋을 것 같습니다.

feat: get all `schedules` by userId

---

apps/server/tsconfig.json
package.json
pnpm-lock.yaml

ts import helper 적용을 위해 tslib 를 추가합니다

chore: tslib

---

apps/server/src/controllers/v1/enquiries.ts
apps/server/src/controllers/v1/events.ts
apps/server/src/controllers/v1/index.ts
apps/server/src/controllers/v1/schedules.ts
apps/server/src/server.ts

router 에 type 을 명시하고 router path 를 복수형으로 수정합니다

fix: router type

---

apps/server/src/types/express.d.ts

express.d.ts 파일을 추가하고 request 에 필요한 필드를 추가하였습니다

chore: add custom field to express request

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts

행사 카테고리를 통한 행사 목록 조회에 사용되는 GET API를 구현하였습니다.

feat: add GET API to get event list of category

---

apps/server/src/middlewares/error.ts
apps/server/src/types/express.d.ts
apps/server/src/utils/logger.ts

response object 에 meta 를 추가하고 api log 에 함께 남도록 수정하였습니다

chore: add meta to response object

---

apps/app/__tests__/App.test.tsx
apps/app/android/settings.gradle
apps/app/ios/Podfile.lock
apps/app/jest.config.js
apps/app/package.json
pnpm-lock.yaml

app test 를 위해 react-native-webview 를 mocking 합니다

test: mock react-native-webview

---

apps/server/src/controllers/v1/schedules.ts

query string type 을 변환해 사용하도록 수정합니다

fix: change query string type for schedule get api

---

.github/auto_assign.yml

chore: auto assign

---

.github/auto_assign.yml

auto assign 파일을 수정합니다
* 전희수님 추가
* pr 작성자만 assignee 에 추가하도록 수정

chore: update auto assign

---

apps/server/package.json
pnpm-lock.yaml

mongoose 와 typgoose version 을 올립니다
https://github.com/Beyond-Imagination/fienmee/security/dependabot/5

chore: upgrade mongoose and typegoose version

---

apps/web/src/app/(navigation)/layout.tsx
apps/web/src/components/navigation/index.ts
apps/web/src/components/navigation/navigation.tsx

하단 네비게이션 추가합니다
현재는 page 이동만 추가하였으며 css 와 svg 수정 필요합니다

feat: navigation

---

apps/app/react-native-config.d.ts
apps/app/src/App.tsx
apps/app/src/pages/Webview.tsx

react native 에 webview page 를 추가합니다

refactor: webview page

---

apps/server/src/config/index.ts
apps/server/src/server.ts

feat: set server host by env

---

README.md

docs: update getting started

---

apps/app/android/app/src/main/res/values/strings.xml
apps/app/app.json
apps/app/ios/app/Info.plist
apps/server/package.json
apps/web/package.json

chore: set app name

---

apps/app/android/app/src/main/java/com/app/MainActivity.kt
apps/app/app.json

ios 이슈가 있어 app name 설정을 수정합니다.
현재 이슈 해결을 위해 임시로 설정하였으며 추후 수정이 다시 필요할수 있습니다

chore: fix app name for ios

---

apps/app/ios/Podfile.lock
apps/app/package.json
apps/app/src/stores/token.ts
pnpm-lock.yaml

mobile 에서 로그인 토큰 관리를 위한 secure storage 를 추가합니다

feat: add token store to mobile app

---

apps/app/android/app/src/main/AndroidManifest.xml
apps/app/android/app/src/main/res/values/strings.xml
apps/app/android/build.gradle
apps/app/ios/Podfile.lock
apps/app/ios/app.xcodeproj/project.pbxproj
apps/app/ios/app/AppDelegate.mm
apps/app/ios/app/Info.plist
apps/app/ios/app/PrivacyInfo.xcprivacy
apps/app/package.json
pnpm-lock.yaml

react native 의 Kakao login 설정을 추가합니다

feat: react native kakao login setting

---

apps/server/src/middlewares/auth.ts

#71 이후 생긴 오류 이슈 해결입니다. path가 잘못 입력되어 있는 문제를 해결합니다.

fix: corrected the import path for isTokenInBlackList

---

apps/app/package.json
pnpm-lock.yaml

https://www.notion.so/beyond-imagination/0d74c042bc884c6ca47acbd5a21f5888?p=11b9ec41642f448c8289ab7778960021&pm=s
참고해주시면 됩니다. 아래 이슈에 자세한 설명이 존재합니다.
https://github.com/facebook/react-native/pull/47641

fix: update React Native to 0.76.3 to resolve Android build issues on Windows

---

apps/app/__mocks__/react-native-encrypted-storage/index.ts
apps/app/ios/SwiftBridge.swift
apps/app/ios/app-Bridging-Header.h
apps/app/ios/app.xcodeproj/project.pbxproj
apps/app/src/api/index.ts
apps/app/src/api/users.ts
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/components/login/OAuthButton.tsx
apps/app/src/components/login/index.ts
apps/app/src/pages/Login.tsx

feat: react native kakao login

---

apps/app/src/App.tsx
apps/app/src/api/users.ts
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/pages/Login.tsx
apps/app/src/pages/Register.tsx
apps/app/src/pages/Webview.tsx
apps/app/src/pages/index.ts

회원가입을 위한 페이지를 추가합니다.
해당 페이지에서 유저 약관 설명 및 개인정보 이용 동의를 받아야 합니다

feat: register page

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts

+ 유저가 작성한 events를 가져올 수 있도록 기존 카테고리를 가져오는 api를 수정합니다.

feat: add get user-created events

---

apps/app/src/api/users.ts
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/pages/Register.tsx
pnpm-lock.yaml

feat: call register api

---

apps/app/src/App.tsx
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/components/login/OAuthButton.tsx
apps/app/src/pages/Register.tsx
apps/app/src/types/index.ts
apps/app/src/types/screen.ts

nativa stack navigator 의 type 을 설정합니다

feat: native stack navigator type

---

apps/app/ios/Podfile.lock
apps/app/ios/app.xcodeproj/project.pbxproj
apps/app/ios/app/Info.plist

fix: ios build

---

apps/web/src/api/event.ts
apps/web/src/components/events/eventDetail.tsx
apps/web/src/components/events/eventOption.tsx

행사 조회 페이지에서 메뉴의 삭제하기 동작을 추가하였습니다.

feat: add event delete action to button

---

apps/app/src/pages/Webview.tsx
apps/app/src/stores/token.ts
apps/web/src/app/layout.tsx
apps/web/src/hooks/bridges/bridge.ts
apps/web/src/hooks/bridges/index.ts

feat: send jwt from app to web

---

apps/app/src/components/login/KakaoLogin.tsx
apps/server/src/middlewares/error.ts
packages/types/api/errors.test.ts
packages/types/api/errors.ts
packages/types/api/index.ts
packages/types/jest.config.json
packages/types/package.json

api 실패후 에러 응답값을 확인하도록 error response type 체크를 추가합니다

feat: error response

---

apps/app/babel.config.js
apps/app/package.json
apps/app/src/App.tsx
apps/app/src/api/users.ts
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/components/login/OAuthButton.tsx
apps/app/src/pages/Login.tsx
apps/app/src/pages/Register.tsx
apps/app/src/pages/Webview.tsx
apps/app/tsconfig.json
pnpm-lock.yaml

react native 에 import alias 를 적용합니다

chore: import alias for react native

---

packages/types/bridges/bridge.ts
packages/types/bridges/index.ts
packages/types/index.ts

app <> web 통신시 사용할 bridge data type 을 추가합니다

feat: add bridge type

---

apps/app/src/pages/Webview.tsx
packages/types/bridges/bridge.ts

application 에서 logout 처리를 추가합니다.
web 에서 bridge 를 통해 logout 요청이 오면 가지고 있는 token 을 삭제하고 login 화면으로 이동합니다

feat: logout on app

---

apps/app/src/pages/Webview.tsx
apps/web/src/hooks/bridges/bridge.ts
packages/types/bridges/bridge.ts

android back button 클릭시 웹뷰내에서 뒤로가도록 합니다

feat: android back button

---

apps/web/src/api/user.ts
apps/web/src/app/(navigation)/setting/page.tsx

logout 버튼 클릭 시 FE에서 BE로 logout 요청을 보냅니다.

feat: add logout request from web to server

---

apps/server/src/app.ts
apps/server/src/controllers/v1/events.ts
apps/server/src/models/category.ts
apps/server/src/models/event.ts
apps/server/src/models/index.ts
apps/server/src/services/seoul/databatch.ts
apps/web/src/app/(backButton)/events/category/page.tsx
apps/web/src/app/(backButton)/events/register/category/page.tsx
apps/web/src/app/(backButton)/events/register/page.tsx
apps/web/src/app/(navigation)/(home)/page.tsx
apps/web/src/app/(navigation)/events/loading.tsx
apps/web/src/app/(navigation)/events/page.tsx
apps/web/src/components/events/categoryItem.tsx
apps/web/src/components/events/eventForm.tsx
apps/web/src/components/header/pageTitle.tsx
apps/web/src/components/navigation/navigation.tsx
apps/web/src/store/category.ts
packages/types/api/category.ts
packages/types/api/events.ts
packages/types/api/index.ts

Event 모델에 사용되는 Category 모델을 추가합니다.

feat: add category model

---

.dockerignore
Dockerfile_SERVER
Dockerfile_WEB
apps/server/package.json
apps/server/src/server.ts
apps/web/next.config.ts
package.json

chore: dockerfile

---

apps/server/src/models/category.ts
packages/types/package.json
pnpm-lock.yaml

fix: fix build fail of category code

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/category.ts
apps/web/src/app/(navigation)/(home)/page.tsx

fix: resolve build error occured by category models

---

apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/pages/Register.tsx
apps/app/src/pages/Webview.tsx
apps/app/src/stores/token.ts
apps/server/src/config/index.ts
apps/server/src/controllers/v1/users.ts
apps/server/src/services/oauth/jwt.ts
packages/types/api/users.ts

login 시 refresh token 도 같이 발급하도록 수정합니다

feat: issue refresh token

---

apps/server/src/controllers/v1/users.ts
apps/server/src/types/errors/jwt/auth.ts
packages/types/api/users.ts

token 을 refresh 하는 api 를 추가합니다

feat: token refresh api

---

apps/app/src/api/users.ts
apps/app/src/pages/Webview.tsx
packages/types/api/users.ts
packages/types/bridges/bridge.ts

web 에서 app 으로 refresh 요청이 오면 access token 을 재발급하고 web 으로 넘겨주도록 하였습니다

feat: refresh token

---

apps/server/src/config/index.ts
apps/server/src/services/oauth/jwt.ts
apps/server/src/types/oauth/jwt.ts
apps/web/package.json
apps/web/src/app/layout.tsx
apps/web/src/config/index.ts
apps/web/src/hooks/bridges/bridge.ts
apps/web/src/libs/fetchIntercept/index.ts
pnpm-lock.yaml

api 호출 전 token 만료 시간을 확인하고 buffer 시간 이내인 경우 refresh 를 요청합니다

feat: refresh token before expire

---

apps/web/src/api/user.ts
apps/web/src/app/(navigation)/setting/page.tsx
apps/web/src/components/settings/deleteAcccountModal.tsx

회원 탈퇴시 FE에서 BE에 회원탈퇴 요청을 보내도록 추가합니다.

feat: add delete account request from web to server

---

apps/web/src/app/(navigation)/setting/page.tsx
apps/web/src/components/settings/deleteAcccountModal.tsx
apps/web/src/hooks/bridges/bridge.ts

refactor: request logout

---

apps/web/src/api/event.ts
apps/web/src/api/schedules.ts
apps/web/src/api/user.ts
apps/web/src/hooks/bridges/bridge.ts
apps/web/src/libs/fetchIntercept/index.ts
apps/web/src/store/accessToken.ts
apps/web/src/store/index.ts

credential 을 zustand middleware 를 이용해 sessionStorage 에서 관리하도록 수정합니다.
그리고 fetch interceptor 를 이용해 credential 을 모든 api 호출에 기본적으로 추가하도록 하였습니다

feat: use zustand for credential

---

apps/app/package.json

react native config 가 내부에 캐싱 파일을 저장하고 있어 제거 하는 스크립트를 추가합니다

feat: remove react native config

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts
apps/web/src/app/(backButton)/events/register/page.tsx
apps/web/src/app/(backButton)/events/update/page.tsx
apps/web/src/components/events/eventForm.tsx
apps/web/src/components/navigation/navigation.tsx
apps/web/src/store/event.ts
packages/types/api/events.ts

이벤트 등록과 수정에서 카테고리 수정 시 입력했던 정보가 사라지는 버그를 수정했습니다.
- Event 모델에 isAllDay 추가(하루종일 체크 여부 확인용)
- 카테고리 수정 후에도 정보가 유지될 수 있도록 eventStore에 있는 정보를 활용하도록 변경

fix: retain existing infomation after modifying categories

---

apps/app/src/components/login/KakaoLogin.tsx

deleted user error 일 경우 회원 가입 페이지로 이동합니다

fix: move to register page with deleted user error

---

apps/web/src/app/layout.tsx
apps/web/src/components/authentication/auth.tsx
apps/web/src/components/authentication/index.ts
apps/web/src/hooks/bridges/bridge.ts

access token 이 만료되었을 경우 loading page 를 표시합니다

feat: show loading page when access token expired

---

apps/server/src/controllers/v1/events.ts

feat: add post event review api

---

Dockerfile_SERVER
package.json
packages/types/.swcrc
packages/types/package.json
packages/types/tsconfig.json
pnpm-lock.yaml

server dockerfile build 시 packages/types 파일의 내용을 같이 build 하도록 합니다

fix: be docker build with types

---

apps/web/src/components/events/dateTimeInput.tsx
apps/web/src/components/events/eventForm.tsx
apps/web/src/components/events/eventTimeSelector.tsx

시작/종료 시간 선택란 간격 조정 및 박스 크기 고정
폰트 크기 및 굵기 통일

feat: improve register page UI (various adjustments)

---

apps/server/src/models/comments.ts
apps/server/src/models/event.ts

feat: add comments model

---

apps/server/src/models/review.ts

의논에서 결정된 사항으로  review 모델의 photo field를 선택사항으로 변경합니다.

feat: make photo field optional in reviews model

---

apps/app/package.json
pnpm-lock.yaml

babel version 을 upgrade 합니다
https://github.com/Beyond-Imagination/fienmee/security/dependabot/14
https://github.com/Beyond-Imagination/fienmee/security/dependabot/13

chore: upgrade babel version

---

.github/workflows/cd.yaml

chore: set docker image tag

---

apps/web/package.json
pnpm-lock.yaml

next 보안 이슈로 인해 최신 버전으로 업그레이드 합니다
https://github.com/Beyond-Imagination/fienmee/security/dependabot/17

chore: upgrade next

---

apps/app/src/pages/Webview.tsx

fix: prevent webview zoom

---

apps/web/src/api/review.ts
apps/web/src/app/(backButton)/events/detail/page.tsx
apps/web/src/app/(backButton)/events/review/create/page.tsx
apps/web/src/app/(backButton)/events/review/page.tsx
apps/web/src/components/authentication/auth.tsx
apps/web/src/components/events/eventDetail.tsx
apps/web/src/components/header/pageTitle.tsx
apps/web/src/components/icon/icon.tsx
apps/web/src/components/modal.tsx
apps/web/src/components/tabBar.tsx
packages/types/api/events.ts

다음과 같은 내용이 추가되었습니다.
+ 리뷰 리스트 페이지 추가 (리뷰 작성 페이지 버튼만 구현 완료)
+ 리뷰 작성 페이지 추가
다음과 같은 내용의 추가 작업이 필요합니다.
+ 리뷰 리스트 조회 및 노출
+ 리뷰 통계 조회 및 노출
+ 리뷰 작성 시 s3 이미지 업로드 도입

feat: add review create page

---

apps/web/src/components/dropdown.tsx
apps/web/src/components/events/eventOption.tsx

event detail page에서 dropdown option 내부 요소들의 간격을 조정합니다.

style: unify styles for Link and button in event option dropdown

---

apps/web/src/components/dropdown.tsx
apps/web/src/components/events/eventDetail.tsx
apps/web/src/components/events/eventOption.tsx
apps/web/src/components/icon/icon.tsx

기존 event detail page의 버튼 위치가 기존 UI 설계와 다른 부분이 있어 UI 설계와 동일하게 수정합니다.

style: update Event detail page to match UI design

---

.gitignore
apps/server/newrelic.js
apps/server/src/server.ts
package.json
pnpm-lock.yaml

chore: set newrelic for server

---

apps/web/src/api/enquiries.ts
apps/web/src/api/event.ts
apps/web/src/api/review.ts
apps/web/src/api/schedules.ts
apps/web/src/api/user.ts

api 에러시 응답받은 body 값을 throw 하도록 수정합니다

fix: throw api error response

---

apps/app/package.json
apps/app/src/App.tsx
pnpm-lock.yaml

react native error boundary 를 추가합니다

feat: add react-native-error-boundary

---

apps/web/src/app/layout.tsx
apps/web/src/components/authentication/auth.tsx
apps/web/src/hooks/bridges/bridge.ts
apps/web/src/providers/bridges/index.tsx
apps/web/src/providers/index.ts
apps/web/src/providers/react-query/index.tsx

root layout 을 server side rendering 을 하도록 수정합니다

feat: use ssr for root layout

---

Dockerfile_SERVER

server dockerfile 에 newrelic 설정 파일을 추가합니다

fix: add newrelic.js to docker image

---

apps/app/src/App.tsx
apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/pages/Error.tsx
apps/app/src/pages/Register.tsx
apps/app/src/pages/index.ts
apps/app/src/types/screen.ts

native error page 를 추가하고 error 발생시 해당 페이지로 이동하도록 수정합니다
error page 디자인은 추후 수정 필요합니다

feat: native error page

---

apps/app/src/pages/Error.tsx

유저가 로그인 되어 있는 상태면 에러페이지에서 웹뷰페이지로 이동하도록 수정하였습니다

feat: move to webview page from error page when user have a token

---

apps/app/src/components/login/KakaoLogin.tsx
apps/app/src/pages/Error.tsx
apps/app/src/pages/Register.tsx
apps/app/src/pages/Webview.tsx
apps/app/src/stores/index.ts

app 코드 정리합니다
* token 저장하는 코드들의 Import 문 수정합니다. 
이슈는 없었는데 /token.ts 와 /token 으로 import 하는 방식이 달라 통합하며 수정하였습니다.
* RegisterScreen 의 navigation props 의 타입이 LoginScreenProps 로 잘못 설정 되어 있어 RegisterScreenProps 로 수정합니다

chore: organize app code

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/comments.ts

feat: get event's comment API

---

apps/app/ios/Podfile.lock
apps/server/src/controllers/v1/schedules.ts
apps/web/package.json
apps/web/src/api/schedules.ts
apps/web/src/app/(navigation)/schedules/page.tsx
apps/web/src/components/schedules/scheduleCalendar.tsx
pnpm-lock.yaml

일정이 있는 날은 캘린더에 점을 표시하도록 수정합니다
아직 캘린더 기본값이 모든 일자에 점을 표시하도록 되어 있어 수정 필요합니다
해당 상태는 캘린더를 클릭하면 풀리게 됩니다

feat: show event day on calendar

---

apps/app/android/app/build.gradle
apps/app/android/app/google-services.json
apps/app/android/app/src/main/AndroidManifest.xml
apps/app/android/app/src/main/java/beyondimagination/fienmee/MainActivity.kt
apps/app/android/app/src/main/java/beyondimagination/fienmee/MainApplication.kt
apps/app/android/build.gradle
apps/app/jest.config.js
apps/app/jest.setup.js
apps/app/package.json
apps/app/src/App.tsx
apps/app/src/services/pushNotificationService.ts
packages/types/api/notification.ts
pnpm-lock.yaml

FCM 안드로이드 푸시메시지 설정을 추가하고, 토큰을 생성하고 단순 메시지를 수신하는 기능을 추가합니다.
이후 다음과 같은 추가 작업이 필요합니다.
+ ios 푸시메시지 설정 추가 (macOS Xocde환경이 필요해 다른분께서 작업해주시면 감사하겠습니다. 참고: https://rnfirebase.io/#3-react-native-cli---ios-setup)
+ 앱에서 토큰 전송 및 서버에서 토큰 수신
+ 앱에서 토큰 갱신 후 서버에서 토큰 업데이트
+ 앱에서 로그인 후 회원 정보에 토큰 관련 데이터 업데이트
+ 서버에서 메시지 전송 시 앱에서 메세지 수신

feat: initialize FCM Android push notification setup

---

apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts

특정 날짜 범위에 해당하는 event 목록을 반환하는 api 를 추가합니다

feat: get /v1/events/category/dates api

---

apps/server/src/controllers/v1/events.ts
apps/web/src/app/(navigation)/(home)/page.tsx

feat: show events of current day on main page

---

apps/server/package.json
apps/server/src/controllers/v1/events.ts
apps/server/src/models/event.ts
pnpm-lock.yaml

특정 기간에서 like 를 가장 많이 받은 event 를 반환하는 api 를 추가합니다

feat: hot event api

---

apps/server/src/controllers/v1/events.ts
apps/web/src/api/event.ts
apps/web/src/components/events/photoUploader.tsx

행사 등록 페이지에서 이미지 업로드 시 사진 미리보기 가능하도록 수정

fix: enable image preview after upload using getObject presigned URL

---

apps/server/src/controllers/v1/events.ts
apps/server/src/middlewares/events.ts
apps/server/src/types/errors/events.ts

feat: add comments modification API

---

apps/web/src/app/(backButton)/events/register/page.tsx
apps/web/src/components/events/photoUploader.tsx

행사 등록, 수정 페이지에서 이미지 업로드 아이콘 및 이미지들이 간혈적으로 가운데에 배치되는 현상을 해결합니다.

fix: resolve photo upload icon centering issue

---

apps/server/src/controllers/v1/users.ts
apps/server/src/models/user.ts

user 의 관심 카테고리를 등록/제거 하는 api 를 추가합니다

feat: user interest api

---

apps/web/src/app/(navigation)/(home)/page.tsx

feat: show interest category list

---

apps/web/src/components/comment/commentInputField.tsx
apps/web/src/components/comment/commentUpdateField.tsx
apps/web/src/components/events/eventForm.tsx
apps/web/src/components/events/eventList.tsx
apps/web/src/components/events/eventOption.tsx
apps/web/src/components/events/photoUploader.tsx
apps/web/src/components/schedules/scheduleDeleteModal.tsx
apps/web/src/components/schedules/scheduleForm.tsx
apps/web/src/components/schedules/scheduleUpdate.tsx

- 기존 alert 혹은 사용자 피드백이 없는 수정, 삭제 요청 부분에서 성공/실패 여부를 toast 메시지로 보여줄 수 있도록 수정합니다.
- 통일성을 위해 문구를 통일합니다.

feat: replace alerts and add toast message for better user feedback

---

apps/server/src/controllers/v1/events.ts

행사 삭제 시 연관된 댓글도 함께 삭제되도록 로직을 추가합니다.

feat: delete related comments when an event is deleted

---

apps/server/src/controllers/v1/events.ts
apps/server/src/controllers/v1/users.ts
apps/server/src/middlewares/auth.ts
apps/server/src/server.ts
apps/web/src/api/user.ts
apps/web/src/components/events/categoryItem.tsx
packages/types/api/users.ts

feat: favorite category

---

apps/server/src/controllers/v1/events.ts
apps/web/src/api/event.ts
apps/web/src/components/comment/comment.tsx
apps/web/src/components/comment/commentOption.tsx
packages/types/api/events.ts

댓글 삭제 기능을 프론트엔드에서 사용할 수 있도록 api 연결했습니다.
테스트 완료했습니다.

feat: enable comment delete on frontend

---

apps/app/package.json
pnpm-lock.yaml

window 에서 디렉토리 삭제를 위해 rimraf 를 사용합니다

chore: use rimraf to delete directory on window

---

apps/web/src/app/(backButton)/events/review/create/page.tsx

리뷰 등록 시 s3 이미지 업로드 기능을 추가합니다. 행사 등록 시 s3 이미지 업로드 로직과 동일하게 작동하도록 작성하였습니다.

feat: implement s3 image upload for review creation

---

apps/web/src/components/comment/comment.tsx
apps/web/src/components/comment/commentLoadingOverlay.tsx
apps/web/src/components/loadingOverlay.tsx

논의사항
- 다른 곳에서도 사용할 수 있도록 컴포넌트화 했습니다.
- 우선순위가 그렇게 높지는 않지만, 사용자 경험 향상을 위해 댓글 등록, 행사 등록 등에도 loading indicator 적용했으면 좋겠습니다.
구현 화면

댓글 삭제 시 Loading Indicator 적용

---

apps/web/src/components/comment/commentInputField.tsx

- 댓글 중복 등록되는 현상을 발견하여 중복등록되지 않도록 방지 로직 추가했습니다.

prevent duplicated comment

---

apps/app/src/pages/Login.tsx

fix: remove unused login button

---

apps/server/src/models/event.ts
apps/server/src/models/review.ts
apps/server/src/models/schedule.ts

서버시작시 typegoose warning 문구 제거를 위해 allowMixed option 을 추가합니다

chore: remove typegoose mixed property warning

---

apps/server/src/utils/logger.ts

feat: remove token information from logging

---

apps/server/src/models/event.ts
apps/server/src/models/schedule.ts
apps/web/src/components/events/eventForm.tsx
apps/web/src/components/schedules/scheduleForm.tsx

종료시간보다 시작시간보다 작거나 같은 경우를 검증하는 로직을 fe, be 모두에 추가합니다.

fix: correct fualty period validation in FE and BE

---

apps/app/android/app/build.gradle

debug 모드 실행시 release 설정 파일이 존재하지 않아도 build가 가능하도록 수정합니다.

chore: improve react-native android build config
