Beyond-Imagination/fienmee

- apps/server/src/models/schedule.ts
* schedule 모델보다 event, user 모델이 먼저 정의되어야합니다.
* 이에 따라서, 현재 `authorId`, `eventId`는 레퍼런스로 연결되어있지 않습니다. 
* 추후에 event, user모델이 추가된다면 레퍼런스로 연결하는 PR을 올릴 예정입니다.
> feat: add `schedule` mongoose model with typescript

- apps/server/src/models/schedule.ts
schedule model의 타입을 string에서 objectId로 변경하였습니다
> refactor: change type of eventId in schedule model

- apps/server/package.json
- apps/server/src/controllers/v1/index.ts
- apps/server/src/controllers/v1/schedule.ts
- apps/server/src/server.ts
<details><summary>이전 내용</summary>
<p>
* 현재는 빠르게 프로토타입만 돌아갈 수 있도록 아래와 같이 구현하였습니다.<br/>
1. 디스크 기반의 저장<br/>
* 추후에 s3 인스턴스가 할당된다면 해당 인스턴스에 저장하도록 수정할게요!<br/>
3. 원본 파일명 저장<br/>
<br/>
* 추후에 `파일 이름 충돌`을 방지하기 위해서 파일명을 해싱한다음 저장하고 `파일 테이블 (원본 파일명, 저장된 파일명)`을 분리하는 것이 어떨까 생각이 드는데요<br/>
* 또, 현재의 요구사항으로는 딱히 보이진 않는데요. 추후에 `일정`에 대한 정보를 `나만 보기`로 설정하는 기능이 추가된다면, 이미지 파일에 대한 접근 권한 또한 생각해야하기 때문에 `파일 서비스`로 아예 분리하는 것도 좋아보입니다.<br/>
</p>
</details> 
---
<리뷰 반영>
* 이미지 업로드 API를 분리하여 구현하는 것으로 결정된 만큼, 기존의 `multipart/form-data`형식의 MIME 타입을 고집할 이유가 없어져서 `application/json` 형식으로 받도록 수정하였습니다.
* 해당 API를 trigger하는 event 의 정보를 포함시키기 위해서 `eventId` 가 request body에 포함되도록 하였습니다.
* 추후 validation middleware를 추가할 예정입니다.
> feat: add `[POST] /schedule` API

- apps/server/src/models/event.ts
+ FE에서 event 모델에 필요한 field를 전부 보내고 있지 않아 해당 건에 대한 수정입니다. 
+ 추가적으로 findByCategory 함수에 Promise가 없어 Promise 반영하였습니다.
> refactor: [BE] add promise return type to findByCategory function and update toJSON method additional fields

- apps/app/.gitignore
- apps/app/android/app/build.gradle
- apps/app/android/app/src/main/java/com/app/MainApplication.kt
- apps/app/android/settings.gradle
- apps/app/ios/Config.xcconfig
- apps/app/ios/Podfile.lock
- apps/app/ios/app.xcodeproj/project.pbxproj
- apps/app/ios/app.xcodeproj/xcshareddata/xcschemes/app.xcscheme
- apps/app/package.json
- apps/app/react-native-config.d.ts
- apps/app/src/App.tsx
- pnpm-lock.yaml
react native 에서 환경변수를 사용할수 있도록 수정합니다
이제 apps/app/.env 파일을 만들고 FE_URL, BE_URL 을 설정할수 있습니다
> feat: react native config

- apps/server/src/controllers/v1/events.ts
* ❌ event 목록 조회 관련된 API에서 limit 크기에 따라서 "원하는 순서"대로 데이터가 전달되지 않음을 확인하였습니다.
* limit 크기가 동일한 경우 동일한 결과를 볼 수 있었던 것은 mongodb의 [쿼리 캐시](https://www.mongodb.com/ko-kr/docs/manual/core/query-plans/) 때문으로 보입니다.
* 프로젝트에서 페이지네이션을 위해 `mongoose-paginate-v2` 를 사용하는데요, 내부 코드를 살펴보면 `mongodb`의 `skip, limit` 기능을 이용하여 페이지네이션을 수행하는 것을 확인하였습니다. 정렬 옵션이 있는 경우 정렬을 가장 먼저 수행하고요 이후에 skip, limit 파이프라인을 따라갑니다.
* [참고](https://github.com/aravindnc/mongoose-paginate-v2/blob/9c1bb84ead9bb23e6cfcf6182094391dfd79b669/src/index.js#L189)
* 문제는 `createdAt` 필드를 기준으로 내림차순 정렬을 수행하는 곳에서 발생했습니다.
* 현재 이벤트의 데이터들은 batch job으로 일괄적으로 db에 저장되었는데요, 그로 인해 중복된 값들이 다수 포진해있었습니다.
* 이로 인해 [tie](https://www.mongodb.com/ko-kr/docs/drivers/go/v1.14/fundamentals/crud/read-operations/sort/#handling-ties)가 발생하였고, 도큐먼트간의 순서를 보장할 수 없었기 때문에 정렬단계에서 …
> fix: paginated result의 inconsistency 수정

- apps/app/react-native-config.d.ts
- apps/app/src/config/index.ts
- apps/app/src/pages/Webview.tsx
react native config 에서 사용하는 type 을 string 으로 변경합니다
> fix: react native config type to string

- apps/app/android/app/src/main/java/com/app/MainApplication.kt
- apps/app/react-native-config.d.ts
- apps/app/src/config/index.ts
- apps/app/src/pages/Webview.tsx
window 환경에서 빌드 시 config의 DEBUG 값이 이미 사용되는 이름이기 때문에 빌드 오류가 발생하였습니다.
이를 해결하기 위해 DEBUG 값을 ENV 값으로 교체하는 작업입니다. 또한 window 환경에서 RNCConfigModule이 두 번 호출되는 경우로 인해 발생하는 실행 오류도 해결을 진행합니다.
> fix: resolve conflicts between default config and .env variables, and prevent duplicate RNCConfigModule loading in Windows environment

- apps/app/src/pages/Webview.tsx
현재 react native환경에서 webview는 스크롤을 진행할 때 overscroll 영역에 대한 액션이 존재했습니다. 이로 인해 header와 navigation이 움직이는 영향이 있습니다. 
UX 측면에서 안좋다고 생각해 해당 action이 동작하지 않게끔 수정합니다.
> fix: disable overScroll effect in Webview for somoother scrolling

- apps/app/android/app/src/main/java/com/app/MainActivity.kt
#64 변경 이후 react native가 실행되지 않는 오류를 해결하기 위해 app name 변경 사항을 android에 추가합니다.  
mac환경에서도 정상동작되는지 확인이 필요합니다.
> fix: update mainActivity.kt to reflect app name change

- apps/web/src/app/(backButton)/layout.tsx
- apps/web/src/app/(navigation)/layout.tsx
- apps/web/src/components/header/logo.tsx
- apps/web/src/components/header/pageTitle.tsx
- apps/web/src/components/navigation/navigation.tsx
현재 layout에서 header와 navigation이 메인 컨텐츠 위에 위치하고 있었습니다. 이 방식의 구조가 아닌 3개의 영역을 독립적으로 구분하기 위해 수정을 진행합니다.
> refactor: separate main content from header and navigation

- apps/server/src/controllers/v1/users.ts
- apps/server/src/models/enquiry.ts
- apps/server/src/models/event.ts
- apps/server/src/models/index.ts
- apps/server/src/models/schedule.ts
- apps/server/src/models/user.ts
#68 이후 생긴 이슈를 해결하기 위한 작업입니다.
typegoose에서 reflect-metadata 라이브러리와 관련된 이슈로, index.ts 파일로 인해 문제가 생긴 것으로 파악됩니다. 
정확한 오류 원인은 파악되지 않았으나, `TimeStamp` class를 가져오는 과정에서 생긴 이슈로 파악됩니다. lib폴더의 파일에서 직접 접근하는 것이 아니라 typegoose에서 접근하도록 수정함으로 해결되었습니다.
다른 방법으로는 저희 프로젝트에 reflect-metadata 라이브러리를 설치한 후 index.ts 파일에서 import하는 방법이 있었습니다.
> fix: resolve Reflect.getMetadata is not function error in typegoose

- apps/server/src/services/seoul/databatch.ts
+ 서울 문화 데이터를 저장하는 로직에서 잘못된 필드를 사용하고 있어 수정을 진행합니다.
+ cost field가 string 값을 저장할 수 있도록 수정합니다.
> fix: corrected field names and data handling in Seoul cultural event storage logic

- apps/web/src/app/(backButton)/events/detail/page.tsx
- apps/web/src/components/events/categoryItem.tsx
- apps/web/src/components/events/event.tsx
- apps/web/src/components/header/pageTitle.tsx
- apps/web/src/store/category.ts
- apps/web/src/store/index.ts
- apps/web/src/store/title.ts
event detail 페이지에서 뒤로가기 버튼을 누르는 경우 category 정보가 모두 삭제되어 category 페이지가 정상동작하지 않는 오류를 해결합니다. 
+ title과 category를 분리합니다. 
+ figma에 따라 detail page로 이동할 때 title이 없도록 변경합니다.
> fix: preserve category information when navigating back from event detail page

- apps/server/src/controllers/v1/events.ts
- apps/web/src/api/event.ts
- apps/web/src/app/(backButton)/events/register/page.tsx
- apps/web/src/app/(backButton)/events/update/page.tsx
- apps/web/src/components/events/dateTimeInput.tsx
- apps/web/src/components/events/eventDetail.tsx
- apps/web/src/components/events/eventForm.tsx
- apps/web/src/components/events/eventOption.tsx
- apps/web/src/components/events/eventTimeSelector.tsx
- apps/web/src/components/events/inputField.tsx
- apps/web/src/store/event.ts
- packages/types/api/events.ts
FE에서 이벤트 수정 기능을 추가하였습니다.
- 수정 버튼 클릭 시 update 페이지로 이동하도록 추가
- update 페이지 수정
- EventForm에서 수정 작업 추가, 기존 이벤트 데이터 사용하도록 추가
- InputField에서 기존 이벤트 값 노출 되도록 추가
추가로, targetAudience가 string 배열인데 string 타입으로 변경하는건 어떤지 의견을 들어보고 싶습니다! 배열에 단일 값으로 DB에 저장이 되는 것 같은데 단일 값만 있으면 굳이 배열로 하지 않아도 될 것 같아서요.
> feat: add event update action to option button

- apps/web/src/api/event.ts
- apps/web/src/components/events/eventForm.tsx
- packages/types/api/events.ts
이벤트를 등록하거나 수정할 때 카테고리 객체가 아닌 id 배열을 저장하도록 변경하였습니다.
현재 카테고리를 수정할 경우 입력했던 데이터가 사라지거나, 이벤트 수정 페이지에서 이벤트 등록 페이지로 이동해버려서 다른 이슈를 진행하면서 수정할 예정입니다.
> refactor: [FE] change types of category in eventForm

- apps/web/src/app/(backButton)/events/category/page.tsx
현재 카테고리 페이지에서 뒤로 가기를 누를 시 다시 한번 'HTTP GET /v1/events/category/?page=1&limit=10’ 요청이 발생하여 오류가 발생.
현재 `(backbutton)/events/category/page.tsx` 에서 뒤로가기 버튼을 누르면 빈 category 정보가 초기화가 됩니다. 그 후에 `router.back()`이 실행됨. 이로 인해 아직 `router.back()`이 실행되기 전에 category 정보가 초기화되고, category._id 값이 변화가 생겼기 때문에 다시 쿼리 요청이 발생하게 됨
1. backbutton 로직 순서 반대로 수정 (다른 페이지에서 위와 같은 이슈가 동일하게 발생할 가능성 존재)
2. 해당 페이지에서는 !category를 통해서 category를 빈 것을 확인하고 있었음. cateogry: string → ICategory로 수정된 이후에 수정되지 않아 비어 있다고 판단하지 못함. 
2번 방법으로 해결
> fix: prevent duplicate API request on back navigation for category page

- apps/server/src/controllers/v1/users.ts
- apps/server/src/models/user.ts
- apps/server/src/services/oauth/auth.ts
- apps/server/src/services/oauth/kakao.ts
- apps/server/src/services/user.ts
- apps/server/src/types/errors/oauth/auth.ts
- apps/server/src/types/errors/oauth/kakao.ts
- apps/server/src/types/oauth/oauth.ts
디비에서 바로 삭제하는 것이 아닌 soft 삭제를 이용하여 isDeleted로 탈퇴회원을 구분하도록 구현하였습니다.
추후 탈퇴 정책을 정의하여 배치를 돌려 주기적으로 삭제하도록 작업할 예정입니다.
> feat: Implement account deactivation using Kakao unlink

- apps/server/src/services/oauth/jwt.ts
lru cache 의 필수 속성을 설정합니다
현재는 임의로 1000으로 설정했습니다.
해당 값은 logout 된 token 을 저장하는 cache 로 1000개 이상 저장이 될 경우 기존 logout 처리한 token 을 다시 사용 가능해집니다
하지만 저희 유저가 1000명 이상이 되기 전까지는 문제가 없을거라 생각됩니다.
추후 실제 유저가 많아지면 해당 값 설정을 변경해야 할수 있습니다
> fix: add lru cache required property

- apps/web/src/app/(backButton)/events/update/category/page.tsx
- apps/web/src/app/(backButton)/events/update/page.tsx
- apps/web/src/components/events/eventForm.tsx
이벤트 수정 페이지에서 카테고리가 제대로 수정되지 않는 현상을 해결하였습니다.
원인
- 카테고리 수정 시 등록 페이지의 카테고리 페이지로 이동 되어 수정된 내용을 제대로 불러오지 못하였음
개선
- 이벤트 수정 내부에 카테고리 페이지를 만들어서 수정의 경우 해당 페이지로 이동하도록 변경
> fix: category update in event update page

- apps/server/src/controllers/v1/events.ts
행사 좋아요 표시를 위한 API를 추가하였습니다.
카테고리에서 행사를 조회할 때 유저의 좋아요 여부를 함께 반환하는 부분을 추가했습니다.
> feat: add event's likes status change API

- apps/app/package.json
- apps/web/src/app/(backButton)/events/category/page.tsx
- apps/web/src/app/(backButton)/layout.tsx
- apps/web/src/app/(navigation)/layout.tsx
- apps/web/src/app/(navigation)/setting/page.tsx
- apps/web/src/app/globals.css
- apps/web/src/components/events/categoryItem.tsx
- apps/web/src/components/events/eventDetail.tsx
- apps/web/src/components/events/eventForm.tsx
- apps/web/src/components/events/eventMap.tsx
- apps/web/src/components/header/logo.tsx
- apps/web/src/components/header/pageTitle.tsx
- apps/web/src/components/icon/icon.tsx
- apps/web/src/components/modal.tsx
- apps/web/src/components/navigation/navigation.tsx
- apps/web/src/components/searchBar.tsx
현재 페이지의 레이아웃에서 디바이스 장치마다 깨지는 부분이 존재합니다. 이를 해결하기 위해 아래와 같은 작업을 수행합니다. 
1. base rem을 조절해 수정을 진행합니다. 이에 따라 기존 px 단위를 rem으로 전부 변경합니다. 
2. h-screen은 하는 경우 특정 환경에서 실제 사용자가 보이는 화면보다 높이가 높게 차지해 불필요한 스크롤을 유발합니다. 그러므로 vh -> dvh로 변경합니다.
> style: apply responsive styles for mobile support

- apps/web/src/api/event.ts
- apps/web/src/components/events/eventDetail.tsx
- apps/web/src/components/events/eventLikes.tsx
- apps/web/src/store/event.ts
- packages/types/api/events.ts
FE에 행사 좋아요 API 연동 작업을 진행하였습니다.
행사 조회 페이지에서 좋아요 표시가 가능합니다.
> feat: add likes function in event detail page

- .github/workflows/cd.yaml
main 브랜치와 develop 브랜치에 코드 push 시 docker image 를 ghcr에 배포합니다
> chore: deploy docker image

- apps/web/src/app/(navigation)/schedules/page.tsx
- apps/web/src/components/icon/schedule.tsx
- apps/web/src/components/schedules/calendar.css
- apps/web/src/components/schedules/scheduleCalendar.tsx
- apps/web/src/components/schedules/sheduleList.tsx
기존 UI 설계와 동일하게 schedule page 의 UI를 소폭 수정합니다.
날짜 위 active icon은 추후 schedule 목록 api를 가져오는 경우 반영될 예정입니다. (현재 조건문이 항상 true)
> style: update Schedule page to match UI Design

- apps/web/src/app/(backButton)/events/error/_error.tsx
- apps/web/src/app/global-error.tsx
- apps/web/src/components/errorPage.tsx
코멘트 반영했습니다
추가수정사항 있으면 말씀해주세요
+ `error: Error & { digest?: string }` 에서 `& { digest?: string }` <- 이부분 선택 옵션인 것 같아서 안넣었는데 혹시 필수로 넣어야 하거나 권장사항이면 말씀해주세요 반영하겠습니다.
> feat: 에러 처리 페이지 생성

- apps/server/src/controllers/v1/schedules.ts
- apps/server/src/middlewares/schedules.ts
- apps/web/src/api/event.ts
- apps/web/src/api/schedules.ts
- apps/web/src/components/schedules/scheduleDetail.tsx
- apps/web/src/components/schedules/scheduleItem.tsx
- apps/web/src/components/schedules/sheduleList.tsx
FE에 일정 상세 조회 기능을 추가하였습니다.
- 기존 코드 변경 사항
- 미들웨어에서 authorId가 일치하는지 확인하는 작업에서 equals를 사용하도록 변경
- 추가된 내용
- 이벤트 상세 조회, 일정 상세 조회 API 추가(FE)
- 일정 내용을 보여줄 수 있는 모달 추가
- 모달에서 행사 더 자세히 보러가기 버튼 클릭 시 해당 이벤트 페이지로 이동하도록 연결
피그마 상으론 좌우 스크롤을 통해 해당 날짜에 다른 일정을 보여줄 수 있는데, 이 부분까지 구현하려면 시간이 더 걸릴 것 같아 우선 TODO로 남기고 조회만 되도록 적용하였습니다.
> feat: add schedule detail modal

- apps/web/src/app/(backButton)/events/register/category/page.tsx
- apps/web/src/components/events/eventForm.tsx
행사 등록 페이지에서 카테고리 수정 후 버튼이 등록하기에서 수정하기로 바뀌는 현상을 수정하였습니다.
원인
- initEvent을 사용해서 어떤 카테고리 페이지로 이동할지 결정해서 등록하기도 수정하기의 카테고리 선택 페이지로 이동
- 등록하기의 카테고리 선택 페이지에서 선택 후 돌아오는 경로가 잘못되어 등록하기 페이지로 돌아오지 못함
해결 방안
- initEvent가 아닌 isRegister를 사용해서 어떤 카테고리 페이지로 이동할지 결정
- 등록하기의 카테고리 선택 페이지에서 이동하는 경로 수정
> fix: event register button name

- apps/web/src/app/(navigation)/(home)/page.tsx
- apps/web/src/components/events/event.tsx
- apps/web/src/components/events/eventList.tsx
- apps/web/src/components/events/previewEventList.tsx
홈 화면의 3개 영역에서 스크롤을 제거하고, 3개의 행사만 보여줄 수 있도록 수정합니다. 
여전히 제목과 다른 내용을 가져오고 있기 때문에 추후 BE api 개발 및 쿼리 요청이 필요합니다.
> style: remove scroll from home screen sections and display 3 events per section

- .github/workflows/cd.yaml
docker image 에 semver 이 기존 2개 설정되어 있었는데 1개만 사용하도록 제거합니다
> chore: remove unnecessary docker version tag

- apps/web/src/components/events/eventTimeSelector.tsx
- apps/web/src/components/schedules/scheduleDetail.tsx
- apps/web/src/components/schedules/scheduleItem.tsx
- apps/web/src/components/schedules/scheduleList.tsx
- apps/web/src/components/schedules/scheduleUpdate.tsx
+ 일정 상세보기에서 좌우 슬라이드로 이전, 이후 schedule을 가져올 수 있도록 합니다. 
+ 일정 상세보기의 화면과 동일하게 update modal의 UI를 조정합니다.
+ figma와 동일하게 UI 간격 조정을 합니다.
> feat: add horizontal slide navigation in schedule detail modal

- apps/web/src/components/comment/commentInputField.tsx
- apps/web/src/components/comment/commentList.tsx
현재 댓글을 등록하면 화면에 즉각 보이지 않고, 다시 eventDetail 페이지를 방문해도 댓글 목록이 갱신되지 않습니다. 이 문제를 해결하고자 다음과 같이 수정합니다.
+ 댓글 등록시 mutation을 이용하고, 성공 시 invalidateQueries를 이용해 댓글 목록을 갱신하도록 합니다.
+ 댓글 목록의 staleTime을 기본값이 아닌 30초로 변경하면서 다른 기기에서도 댓글 목록을 빠르게 갱신할 수 있도록 합니다. 
+ 30초로 선정한 이유는 0초로 하면 불필요한 갱신이 많이 반복되고, 60초 이상일 시 갱신이 비교적 느리게 갱신될 것으로 판단되어 30초로 선정하였습니다.
> fix: immediately refetch comments after submission to update the view

- apps/server/src/controllers/v1/events.ts
- apps/server/src/models/comments.ts
- apps/web/src/api/event.ts
- apps/web/src/components/comment/comment.tsx
- apps/web/src/components/comment/commentOption.tsx
- apps/web/src/components/comment/commentUpdateField.tsx
- packages/types/api/events.ts
댓글 수정이 가능하도록 FE에 로직을 추가합니다.
- 댓글 옵션을 클릭할 수 있도록 `isAuthor` field를 comment에 추가합니다.  
- 댓글 수정이 가능하도록 UI를 추가합니다.
<div style="display: flex; gap: 1rem;">
</div>
> feat: enable comment editing on frontend

- apps/web/src/components/events/eventForm.tsx
- apps/web/src/components/events/eventOption.tsx
- 라우터 경로를 해당 페이지 뒤로가기로 변경했습니다.
- 캐시 새로고침을 통해 변경된 정보를 바로 반영할 수 있도록 했습니다.
> refactor : refetch query cache after event create, update, and delete

- apps/web/src/components/events/event.tsx
- apps/web/src/components/events/eventList.tsx
행사 목록을 카테고리를 통해 조회할 때 각 행사 컴포넌트 요소들에서 이미지의 크기가 부모 요소를 넘치는 문제가 있었습니다. 이로 인해 무한스크롤에 필요한 ref 객체가 화면에 보이지 않아 무한 스크롤이 특정 시점에서 동작하지 않는 문제가 있었습니다. 이를 해결하기 위해 컴포넌트의 UI를 조정합니다.
> fix: issue with observer ref not being rendered in viewport

- apps/web/src/app/(navigation)/events/loading.tsx
FE에서 /events 페이지에 최초 접근 시 로딩화면에서 보여지는 "내가 등록한 행사", "인기 행사" 카테고리를 선택하는 경우 잘못된 접근이 발생하는 이슈를 해결합니다. 또한, 스켈레톤을 추가하여 자연스럽게 카테고리가 로드되는 것처럼 보이게 수정합니다.
> fix: prevent incorrect navigation when clicking category during iniaital load

- apps/web/src/app/(backButton)/layout.tsx
- apps/web/src/app/(navigation)/layout.tsx
- apps/web/src/components/header/logo.tsx
- apps/web/src/components/header/pageTitle.tsx
- apps/web/src/components/layout/BaseLayout.tsx
- apps/web/src/components/navigation/navigation.tsx
현재 레이아웃에서 메인 콘텐츠 요소를 보여주는 화면에서 헤더의 크기가 순간적으로 변경되는 문제, 헤더와 네비게이션 바가 너무 많은 영역을 차지하는 문제를 해결하기 위해 다음과 같은 작업을 수행합니다. 
- (backButton)과 (navigation) 부분의 레이아웃의 요소의 영역을 공통으로 관리하기 위해 `BaseLayout` 컴포넌트를 생성합니다.
- 두 종류의 헤더(`logo.tsx`, `pageTitle.tsx`)의 높이를 5rem으로 줄입니다.
- `navigation`의 높이를 7rem에서 6.25rem으로 변경하면서 아이콘의 크기를 줄이고, 추가 버튼이 올라오는 높이도 3.5rem으로 조정합니다.
변경 전과 후 사진은 다음과 같습니다.
> refactor: layout structure and improve UI/UX

- apps/web/src/app/(backButton)/events/register/page.tsx
- apps/web/src/app/(backButton)/events/review/create/page.tsx
- apps/web/src/app/(backButton)/events/update/page.tsx
- apps/web/src/components/events/EventImage.tsx
- apps/web/src/components/events/event.tsx
- apps/web/src/components/events/eventForm.tsx
- apps/web/src/components/events/eventPhoto.tsx
- apps/web/src/components/events/photoUploader.tsx
- apps/web/src/components/review/ReviewImage.tsx
- apps/web/src/components/review/review.tsx
- apps/web/src/hooks/s3/index.ts
- apps/web/src/hooks/s3/useImageLoader.ts
- apps/web/src/hooks/s3/useS3Upload.ts
리뷰 등록, 일정 등록 및 일정 수정 시 이미지 업로드에 S3 Presigned URL을 사용하고 있었습니다. 그러나 Presigned URL의 만료로 인해 시간이 지나면 이미지 링크가 깨지는 문제가 발생했습니다. 이러한 이슈를 해결하기 위해 이미지 저장 방식을 다음과 같이 수정하였습니다.
주요 변경사항은 다음과 같습니다:
- s3 key 기반관리: 사용자가 업로드한 이미지는 이제 Presigned URL이 아닌 S3 Key 값으로 관리됩니다.
- `useS3Upload` 훅 도입: s3 이미지를 업로드하고 해당 s3 키를 반환하는 로직을 캡슐화합니다.
- `useIamgeLoader` 훅 도입: S3 Key를 기반으로 필요한 시점에 이미지 URL을 동적으로 로드합니다.
-  새로운 이미지 표시 컴포넌트 도입: `EventImage`, `ReviewImage` 컴포넌트를 통해 이미지 로드 및 오류, 로딩 처리를 합니다.
추가적으로, 이미지 로딩 성능 향상과 비용 효율성을 위해 향후 CloudFront 도입을 고려할 수 있습니다. 이를 통해 Presigned URL을 지속적으로 생성하는 비용을 제거하고, 이미지 접근 속도도 개선할 수 있습니다.
> refactor: image handling to use s3 key instead of presigned URLs

- apps/server/src/controllers/v1/events.ts
- apps/web/src/app/(backButton)/events/category/page.tsx
카테고리 페이지에서 인기행사 카테고리에 접근할 때 pagination data를 리턴하고 있지 않아 페이지 접근이 되지 않는 문제를 해결하기 위해 paginatio data를 리턴합니다. 
특정 카테고리 _id 에 요청을 보낼 때 (HOTEVENT 등)에서 요청 자체에서 오류가 발생하는 문제가 생겨 .toString() 함수를 추가합니다.
> fix: return pagination data for HOTEVENT category requests

- apps/server/src/models/user.ts
- apps/server/src/scheduler.ts
- apps/server/src/services/user.ts
회원 탈퇴한 유저의 정보를 자동으로 삭제하는 기능을 개발하였습니다.
- 자동으로 유저 모델에서 데이터를 삭제하는 스케쥴러 함수 추가
- 현재는 updatedAt이 1달 지났고 isDeleted가 true인 유저의 데이터를 삭제하고 있습니다.
TODO
- 회원 탈퇴 API에서 회원의 닉네임을 변경하는 작업이 필요합니다.
> feat: automatically delete withdrawn member information

- apps/server/src/models/schedule.ts
- apps/web/src/components/schedules/scheduleDetail.tsx
- apps/web/src/components/schedules/scheduleItem.tsx
- apps/web/src/components/schedules/scheduleList.tsx
- 행사 조회 API에 기본 정렬 추가 (isAllDay 우선, startDate/ endDate 오름차순)
- 기존 하루종일 일정 표시 방식을 '하루 종일' 라벨로 변경하여 가독성 향상
> feat: improve all-day event display and sorting logic
